info:
  component: ldap group microservices

server:
  port: 8081
spring:
  application:
    name: ldap-group-services
  datasource:
    url: jdbc:sqlserver://172.20.16.3:1433;databaseName=ldap_group_db
    username: back_gasel
    password: GASEL@dbPass
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  second-datasource:
    url: jdbc:sqlserver://172.20.16.3:1433;databaseName=ebx_gasel_db
    username: back_gasel
    password: GASEL@dbPass
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
    #      ddl-auto: create-drop
    show-sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  batch:
    job:
      enabled: false
    initialize-schema: always
cron:
  expression: "*/10 * * * * *"
#flyway:
#  enabled: true
#  locations: classpath:db/migration
#  encoding: UTF-8

group-ldap:
  client:
    personEbxProxy: 'http://172.20.16.5:8888/ebx/parametres'
    structureEbxProxy: 'http://172.20.16.5:8888/ebx/structure'
    parameterEbxProxy: 'http://172.20.16.5:8888/ebx/parametres'
    ldapPort: 389
    ldapHostName: 172.20.16.4
    ldapBindPassword: esDAPsmbP
    ldapBaseDn: dc=cfdt,dc=fr
    ldapBindDN: cn=admin,dc=cfdt,dc=fr