info:
  component: ldap group microservices

server:
  port: 8081

spring:
  application:
    name: ldap-group-services
  datasource:
    url: jdbc:sqlserver://192.168.1.185:1433;databaseName=ldap_group_db
    username: gasel_back
    password: gasel
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  second-datasource:
    url: jdbc:sqlserver://192.168.1.185:1433;databaseName=ebx_gasel_db
    username: gasel_back
    password: gasel
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
    #      ddl-auto: create-drop
    show-sql: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  batch:
    job:
      enabled: false
    initialize-schema: always
cron:
  expression: "*/10 * * * * *"
#flyway:
#  enabled: true
#  locations: classpath:db/migration
#  encoding: UTF-8

security:
  cas:
    proxy-validation:
      chains:
        - http://localhost:8180, http://localhost:8181
        - - http://localhost:8280
          - http://localhost:8281
    server:
      base-url: http://localhost:8080/cas/
      protocol-version: 3
      logoutURL: http://172.20.16.4:8445/cas-gasel/logout
    service:
      resolution-mode: dynamic
    redirect:
      serverName: http://localhost:8080/gaselweb
    ticket:
      validation:
        tolerance: 500000
    securityContext:
      serviceProperties:
        service: http://172.20.16.4:8445/cas-gasel/services/j_acegi_cas_security_check
        adminRoles: ROLE_ADMIN
      casProcessingFilterEntryPoint:
        loginUrl: http://172.20.16.4:8445/cas-gasel/login
      ticketValidator:
        casServerUrlPrefix: http://172.20.16.4:8445/cas-gasel
    themeResolver:
      defaultThemeName: recette
    authentication:
      throttling:
        failureRangeInSeconds: 60
        failureThreshold: 5
        delay: 10000

group-ldap:
  client:
    ldapPort: 389
    ldapHostName: 172.20.16.4
    ldapBindPassword: esDAPsmbP
    ldapBaseDn: dc=cfdt,dc=fr
    ldapBindDN: cn=admin,dc=cfdt,dc=fr
#    nombre de jour
    delai: 3