info:
  component: ldap group microservices

server:
  port: 8081

spring:
  application:
    name: ldap-group-services
  datasource:
    url: jdbc:sqlserver://192.168.1.185:1433;databaseName=ldap_group_db
    username: gasel_back
    password: gasel
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  second-datasource:
    url: jdbc:sqlserver://192.168.1.185:1433;databaseName=ebx_gasel_db
    username: gasel_back
    password: gasel
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
    #      ddl-auto: create-drop
    show-sql: true
  cache:
    type: redis
  redis:
    host: redis
    port: 6379
  batch:
    job:
      enabled: false
    initialize-schema: always
cron:
  expression: "*/10 * * * * *"

group-ldap:
  client:
    ldapPort: 389
    ldapHostName: 172.20.16.4
    ldapBindPassword: esDAPsmbP
    ldapBaseDn: dc=cfdt,dc=fr
    ldapBindDN: cn=admin,dc=cfdt,dc=fr
#    nombre de jour
    delai: 3

