version: '3.3'

services:
  backend:
    build:
      context: ../
      dockerfile: ./docker/backend/Dockerfile
    depends_on:
      - redis
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ../
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  redis:
    image: redis:latest
  
