CREATE TABLE LDAP_GROUP_REQUEST (
  ID_REQUEST           numeric(19,0)   identity(1,1) not null,
  REQUEST           TEXT,
  CREATION_DATE         DATETIME,
  LAST_EXECUTION_DATE   DATETIME,
  EXECUTOR   VARCHAR (255),
  PRIMARY KEY (ID_REQUEST)
);

CREATE TABLE LDAP_GROUP (
  ID_LDAP_GROUP numeric(19,0)   identity(1,1) not null,
  ID_REQUEST           numeric(19,0) NOT NULL,
  NAME            VARCHAR(50),
  DESCRIPTION        TEXT,
  MEMBERS_NUMBER    VARCHAR (255),
  PRIMARY KEY (ID_LDAP_GROUP),
  FOREIGN KEY (ID_REQUEST) REFERENCES LDAP_GROUP_REQUEST (ID_REQUEST)
);
